### ISSUE TITLE
Error in rendering

### ISSUE THREAD

**Issue by tbhaxor** [obedm503/katex-latex#13]
I am using it with Vue-ShowDown and Getting this error

![image](https://user-images.githubusercontent.com/28386721/63123679-2ca63d00-bfc7-11e9-806b-3872d80cf300.png)

**My Complete Code Goes Here**

```vue
<template>
  <div>
    <center>
      <p>Enter the Latex</p>
      <p>
        <v-flex xs6 offset-xs1>
          <v-textarea label="Latex" v-model="data"></v-textarea>
        </v-flex>
      </p>
    </center>
    <VueShowdown style="font-size:30px" :markdown="data" :extensions="[highlight, katex]" />
  </div>
</template>

<script>
import ShowdownHighlight from "showdown-highlight";
import ShowdownKatex from "showdown-katex";
export default {
  name: "App",
  components: {},
  data: () => ({
    data: "",
    highlight: ShowdownHighlight,
    katex: ShowdownKatex({
      // maybe you want katex to throwOnError
      throwOnError: true,
      // disable displayMode
      displayMode: false,
      // change errorColor to blue
      errorColor: "#1500ff"
    })
  }),
  created() {}
};
</script>
```

**Comment by obedm503** [comment]
hi, would you mind recreating this with just showdown and showdown-katex without anything extra like vue

**Comment by tbhaxor** [comment]
Sure

**Comment by tbhaxor** [comment]
@obedm503  Same error

![image](https://user-images.githubusercontent.com/28386721/63196522-1960a380-c093-11e9-893c-729d767dabf9.png)

**Comment by tbhaxor** [comment]
and also tell me how to decrease this padding 

![image](https://user-images.githubusercontent.com/28386721/63196807-d7842d00-c093-11e9-967b-13d61a7c6953.png)

**Comment by obedm503** [comment]
I meant if you could create a repo where I could reproduce the error while trying to keep it as simple as possible

**Comment by tbhaxor** [comment]
> I meant if you could create a repo where I could reproduce the error while trying to keep it as simple as possible

This is my second project. In the first project, I used pure js from CDN. Still the same issue. So i thought what if vue-showdown has overcome

**Comment by obedm503** [comment]
could you share a single `.html` file demonstrating this bug just using `showdown` and `showdown-katex`, so that I can reproduce it on my own?

otherwise, I really can't help

**Comment by tbhaxor** [comment]
I got no error in HTML
but when i use it in vue js, even though native i get the error

**Comment by obedm503** [comment]
Then it's safe to say that the error is not with showdown-katex but with vue somehow
