### ISSUE TITLE
Latex Modifiers are not Rendered

### ISSUE THREAD

**Issue by tbhaxor** [obedm503/katex-latex#14]
**Describe the bug:**
There is rendering issue when using katex and latex modifiers

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
~${\displaystyle |\psi \rangle =\alpha |0\rangle +\beta |1\rangle }~
```
use this same code and text on https://katex.org/

**Expected behavior:**

![](https://latex.codecogs.com/gif.latex?${\displaystyle%20|\psi%20\rangle%20=\alpha%20|0\rangle%20+\beta%20|1\rangle%20}$)

_from: latex.codecogs.com_

**Screenshots:**

![image](https://user-images.githubusercontent.com/28386721/63653380-8954e500-c789-11e9-8dce-5e9ff58d3f40.png)

`le` of displaystyle is rendered :man_facepalming: 

**Environment (please complete the following information):**
 - KaTeX Version: ^0.10.1 with 
 - Device: Desktop
 - OS: Arch Linux
 - Browser: Any
 - Version: Any

**Comment by obedm503** [comment]
you're using the wrong delimiters. Anything between `~` characters is treated as asciimath and is converted through a different process. If you want inline latex, then you should use `$$` as delimiters instead.

Here's a demo, tested on the [homepage](https://obedm503.github.io/showdown-katex/)
![image](https://user-images.githubusercontent.com/9118707/63658112-d32fd200-c76d-11e9-8290-3439514b0bb4.png)
