### ISSUE TITLE
Formulas that contain markdown characters (e.g. '_' for italic) not rendered correctly

### ISSUE THREAD

**Issue by thilo-behnke** [obedm503/katex-latex#15]
Hi,

We found the following issue in our project: https://github.com/ls1intum/Artemis/issues/768

E.g. the formula `$ a_0 + a_1 $` is not displayed correctly for us, as the html that the extension receives already splits this expression into 3 separate nodes:

0: text -> "$ a"
1: em -> "0 + a"
2: text -> "1 $"

I wonder if the extension should use the type 'lang' instead of 'output', but would be interested in your opinion on this matter:
https://github.com/obedm503/showdown-katex/blob/master/src/showdown-katex.js#L71

**Comment by obedm503** [comment]
This is because `$` are not valid delimiters, use `$$` instead. This is an error with the documentation.

Testing in the [demo site](https://obedm503.github.io/showdown-katex/)
![image](https://user-images.githubusercontent.com/9118707/64059213-593c8600-cb7d-11e9-81de-608ed4316976.png)
