### ISSUE TITLE
Use $$ for display mode math?

### ISSUE THREAD

**Issue by lriuui0x0** [obedm503/katex-latex#18]
Is there a way to use $$..$$ for display mode math? I tried to use the following options

```
delimiters: [
    { left: "$$", right: "$$", display: true },
    { left: "$", right: "$", display: false },
],
```

but it doesn't work.

**Comment by obedm503** [comment]
Confirmed. It happens because default delimiters are passed to katex first.

**Comment by obedm503** [comment]
it should now allow you to override default delimiters. this has not been released yet.
