### ISSUE TITLE
Invalid rendering or rendering error

### ISSUE THREAD

**Issue by Fullsize** [obedm503/katex-latex#20]
expected result
![image](https://user-images.githubusercontent.com/30223113/82277354-30ce1380-99ba-11ea-9220-9ee2bc5a802b.png)

actual effect
![image](https://user-images.githubusercontent.com/30223113/82277379-49d6c480-99ba-11ea-937f-47875ae92bcd.png)

code
![image](https://user-images.githubusercontent.com/30223113/82277434-6a068380-99ba-11ea-92ea-1d753bb62fbc.png)
![image](https://user-images.githubusercontent.com/30223113/82277464-7e4a8080-99ba-11ea-9be6-ca01db379460.png)

**Comment by obedm503** [comment]
Can you give more information, like what the input (`option.value`) is? To my knowledge, [it works](https://obedm503.github.io/showdown-katex/?source=%23%23%23%23+It+works%0A%0A%60%60%60asciimath%0Ae+%3D+mc%5E2%0A%60%60%60%0A~e%3Dmc%5E2~%0A%0A%0A%60%60%60latex%0Ae+%3D+mc%5E2%0A%60%60%60%0A%24%24e%3Dmc%5E2%24%24). (Scroll down to "Try the live demo")

**Comment by Fullsize** [comment]
> Can you give more information, like what the input (`option.value`) is? To my knowledge, [it works](https://obedm503.github.io/showdown-katex/?source=%23%23%23%23+It+works%0A%0A%60%60%60asciimath%0Ae+%3D+mc%5E2%0A%60%60%60%0A~e%3Dmc%5E2~%0A%0A%0A%60%60%60latex%0Ae+%3D+mc%5E2%0A%60%60%60%0A%24%24e%3Dmc%5E2%24%24). (Scroll down to "Try the live demo")

option.value: `一，$$e=mc^2$$`

**Comment by obedm503** [comment]
It still seems to work just fine. https://obedm503.github.io/showdown-katex/?source=%E4%B8%80%EF%BC%8C%24%24e%3Dmc%5E2%24%24

**Comment by Fullsize** [comment]
> It still seems to work just fine. https://obedm503.github.io/showdown-katex/?source=%E4%B8%80%EF%BC%8C%24%24e%3Dmc%5E2%24%24

It seems that the style is not in effect

**Comment by obedm503** [comment]
Are you including the necessary katex stylesheet? https://katex.org/docs/browser.html

**Comment by Fullsize** [comment]
> Are you including the necessary katex stylesheet? https://katex.org/docs/browser.html

external reference to katex solved the problem, I will close the problem
