### ISSUE TITLE
Add KaTeX basic auto-render extension

### ISSUE THREAD

**Issue by benoit-sbr** [obedm503/katex-latex#3]
Hi!

Thank you for your very useful project. I am already using it in combination with bootmark, it is great. I am wondering if you are planning to add the auto-render extension of KaTeX [see here](https://github.com/Khan/KaTeX/commit/cd9bca4a89eddd77c542e23a4a9dc2deff2ab72c).

This allows to simply enter LaTeX commands between $ signs in the web pages.

Thank you for your help,
Cheers.

**Comment by obedm503** [comment]
So, if I understand correctly, the purpose of the auto-render extension is to render things inline, hence removing the need for any custom markdown language support (`asciimath` and `latex`)? 

When this project started, this was one of the main features missing. I'll look into it and get back to you.

**Comment by benoit-sbr** [comment]
This is also what I understand. Thanks!

**Comment by obedm503** [comment]
I've been looking into it, and it's added in the development branch. should be in master and new version published when I figure out bundling. this will be a breaking change. I'll close the issue when new version is released.

**Comment by benoit-sbr** [comment]
Great! You were amazingly fast obedm503. I'll give you a feedback when it's released.

**Comment by obedm503** [comment]
version 0.3.2 should address this. let me know of any problems. there are still no examples to demo this feature, PRs welcome

**Comment by benoit-sbr** [comment]
Again, that's amazing. I was using your extension with a line

    <script src="https://obedm503.github.io/katex-latex/dist/katex-latex.bundle.min.js"></script>
in my `index.html`.

I changed the link to `katex-latex.min.js` as you suggested, but there is nothing there. What could I do?

**Comment by obedm503** [comment]
I forgot to mention that I'm no longer including the dist folder in github. You'll have to use https://unpkg.com/katex-latex@0.3.2/dist/katex-latex.min.js you can also replace the version number for "latest"

**Comment by benoit-sbr** [comment]
OK. I could manage to have the inline math rendering working :)

I'll update with my feedback on the other issue you opened.

**Comment by obedm503** [comment]
the demo in the project page should serve as a starting point. try it out here: https://obedm503.github.io/katex-latex/ source here: https://github.com/obedm503/katex-latex/blob/master/index.html
