### ISSUE TITLE
NPM version

### ISSUE THREAD

**Issue by leon-vv** [obedm503/katex-latex#8]
Hello,

Thanks for sharing this plugin.
I noticed the [npm package](https://www.npmjs.com/package/showdown-katex) is three years old. How can we install the version in this repository? I failed to generate the `dist/` directory.

**Comment by obedm503** [comment]
I recently took over the package name, but haven't been able to publish. The previous package name was katex-latex. Try installing from there and ignore the deprecation warning for the time being
