### ISSUE TITLE
It seems the matrix output don't correct

### ISSUE THREAD

**Issue by garyyan** [obedm503/katex-latex#9]
I input the matrix,for example
 `$ \begin{matrix} 1 & 2 \\ 3 & 4 \\ \end{matrix} $`,
But the output seems don't correct
Would you like to give me some suggestion?
thanks a lot

**Comment by obedm503** [comment]
I tried `\\[ \begin{matrix} 1 & 2 \\\ 3 & 4 \\ \end{matrix} \\]` and it works as expected. But it seems the `$` separator is not working correctly. Will investigate

**Comment by obedm503** [comment]
also tested `$$ \begin{matrix} 1 & 2 \\\ 3 & 4 \\ \end{matrix} $$` and


    ```latex
    \begin{matrix} 1 & 2 \\\ 3 & 4 \\ \end{matrix}
    ```
they both work
